/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AbbButton {
    'color': 'default' | 'primary' | 'secondary' | undefined;
    'type': 'button' | 'submit' | undefined;
    'variant': 'text' | 'outlined' | 'contained' | undefined;
  }
  interface AbbHeader {}
  interface AbbHome {}
  interface AbbRoot {}
  interface AbbTypography {
    'variant': 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | undefined;
  }
}

declare global {


  interface HTMLAbbButtonElement extends Components.AbbButton, HTMLStencilElement {}
  var HTMLAbbButtonElement: {
    prototype: HTMLAbbButtonElement;
    new (): HTMLAbbButtonElement;
  };

  interface HTMLAbbHeaderElement extends Components.AbbHeader, HTMLStencilElement {}
  var HTMLAbbHeaderElement: {
    prototype: HTMLAbbHeaderElement;
    new (): HTMLAbbHeaderElement;
  };

  interface HTMLAbbHomeElement extends Components.AbbHome, HTMLStencilElement {}
  var HTMLAbbHomeElement: {
    prototype: HTMLAbbHomeElement;
    new (): HTMLAbbHomeElement;
  };

  interface HTMLAbbRootElement extends Components.AbbRoot, HTMLStencilElement {}
  var HTMLAbbRootElement: {
    prototype: HTMLAbbRootElement;
    new (): HTMLAbbRootElement;
  };

  interface HTMLAbbTypographyElement extends Components.AbbTypography, HTMLStencilElement {}
  var HTMLAbbTypographyElement: {
    prototype: HTMLAbbTypographyElement;
    new (): HTMLAbbTypographyElement;
  };
  interface HTMLElementTagNameMap {
    'abb-button': HTMLAbbButtonElement;
    'abb-header': HTMLAbbHeaderElement;
    'abb-home': HTMLAbbHomeElement;
    'abb-root': HTMLAbbRootElement;
    'abb-typography': HTMLAbbTypographyElement;
  }
}

declare namespace LocalJSX {
  interface AbbButton {
    'color'?: 'default' | 'primary' | 'secondary' | undefined;
    'type'?: 'button' | 'submit' | undefined;
    'variant'?: 'text' | 'outlined' | 'contained' | undefined;
  }
  interface AbbHeader {}
  interface AbbHome {}
  interface AbbRoot {}
  interface AbbTypography {
    'variant'?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | undefined;
  }

  interface IntrinsicElements {
    'abb-button': AbbButton;
    'abb-header': AbbHeader;
    'abb-home': AbbHome;
    'abb-root': AbbRoot;
    'abb-typography': AbbTypography;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'abb-button': LocalJSX.AbbButton & JSXBase.HTMLAttributes<HTMLAbbButtonElement>;
      'abb-header': LocalJSX.AbbHeader & JSXBase.HTMLAttributes<HTMLAbbHeaderElement>;
      'abb-home': LocalJSX.AbbHome & JSXBase.HTMLAttributes<HTMLAbbHomeElement>;
      'abb-root': LocalJSX.AbbRoot & JSXBase.HTMLAttributes<HTMLAbbRootElement>;
      'abb-typography': LocalJSX.AbbTypography & JSXBase.HTMLAttributes<HTMLAbbTypographyElement>;
    }
  }
}


